name: tasks
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2+12

environment:
  sdk: ^3.5.0

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  go_router: ^14.2.7
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  http: ^1.5.0
  shared: ^1.0.0
  custom_adaptive_scaffold: ^2.0.2
  server:
    path: ../server
  shelf: ^1.4.2
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  msix: ^3.16.12
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

msix_config:
  display_name: Tasks
  publisher_display_name: Levi Lesches
  identity_name: dev.levi.tasks
  msix_version: 2.0.2.12
  logo_path: icon.png

flutter_launcher_icons:
  image_path: icon.png
  android: true
  windows:
    generate: true