name: tasks
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
