name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# resolution: workspace
dependencies:
  mdns_dart: ^2.1.0
  shared:
    path: ../shared
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0

