name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# resolution: workspace
dependencies:
  mdns_dart: ^2.1.0
  shared:
    path: ../shared
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0

dependency_overrides:
  # Version 2.1.0 has a bug in parsing IPv6 addresses.
  # We don't use IPv6 but that bug throws an error during all mDNS responses
  # See: https://github.com/animeshxd/mdns_dart/issues/12
  mdns_dart:
    git: https://github.com/animeshxd/mdns_dart
