name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
resolution: workspace
dependencies:
  uuid: ^4.5.1
  collection: ^1.19.1
  meta: ^1.16.0
  mdns_dart: ^2.1.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

dependency_overrides:
  # Version 2.1.0 has a bug in parsing IPv6 addresses.
  # We don't use IPv6 but that bug throws an error during all mDNS responses
  # See: https://github.com/animeshxd/mdns_dart/issues/12
  mdns_dart:
    git: https://github.com/animeshxd/mdns_dart
